name: "Reviewer Roulette"

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

jobs:
  assign_random_reviewers:
  
    runs-on: ubuntu-latest
    
    permissions: write-all
      
    name: Assign random reviewers to pull requests
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assign random reviewers to PR
        uses: ihs7/action-reviewer-roulette@v1
        with:
          number-of-reviewers: 2
